set nocompatible

imap jj <Esc>

filetype plugin indent on
syntax on

set sw=2 sts=2 et ws ic sc is hls wrap hid so=3

colorscheme delek

nmap Y y$

map <c-j> <c-e>
map <c-k> <c-y>
map -<space> :noh<cr>

au BufEnter *.java map -c :up<cr>:make %<.class && java %< < %<.in<cr>
au BufEnter *.cpp map -c :up<cr>:make %< && ./%< < %<.in<cr>
