set nocp

imap jj <Esc>

set sw=2 sts=2 et ws ic sc is hls wrap hid so=3 gd

colorscheme delek

nmap Y y$

map <c-j> <c-e>
map <c-k> <c-y>
map -<space> :noh<cr>
map -i :e %<.in<cr>

map -c :up<cr>:make<cr>

au BufEnter *.cpp set mp=make\ %< | map -h :!./%< < %<.in<cr>
au BufEnter *.java set mp=make\ %<.class | map -h :!java %< < %<.in<cr>

filetype plugin indent on
syntax on

